#Probe参数配置
jz:
  probe:
    key: a834ad5e-0d70-86c3-8b4a-c0c3bfdbe5f5
    name: 事件宝事件网关
    type: DISPATCHER
    eventSourceType: PROBE
    version: 1.0
    #接收事件端口
    port: 22222
    #Probe并发处理能力，为0时根据系统CPU个数自动适配
    threadCount: 1
#项目信息
project: 
  id: 10
  name: Your Event
#disptcher策略，batch数量，interval周期，两个任何一个先满足就开始dispatcher
dispatcher:
  batch: 1000
  #间隔周期，单位s
  interval: 2
  timerEnable: true
handler: 
  data[0]:
  # type is EventSourceType
  #不同type的事件消息可以被路由到同一个host和port（同一个事件处理引擎）
    type: RESTAPI
    host: localhost
    port: 33333
    enable: true