#Probe参数配置
jz: 
  probe:
    key: a834ad5e-0d70-86c3-8b4a-c0c3bfdbe5f5
    name: zabbix-handler
    type: HANDLER
    eventSourceType: ZABBIX
    version: 1.0
    #接收事件端口
    port: 33333
    #与Dispatcher线路检测间隔，单位秒
    #Probe并发处理能力，为0时根据系统CPU个数自动适配
    threadCount: 1
#项目信息
project: 
  id: 10
  name: Your Event
rules: 
  jdbc: 
    driverClassName: org.postgresql.Driver
    databaseType: postgresql
    url: jdbc:postgresql://localhost:5432/ueh?currentSchema=ueh_admin&TimeZone=PRC
    username: root
    password: 123456
            # 初始连接数
    initialSize: 5
            # 最小连接池数量
    minIdle: 10
            # 最大连接池数量
    maxTotal: 20
            # 配置获取连接等待超时的时间
    maxWaitSeconds: 60  
delivery: 
  data[0]:
    type: EMAIL
    host: localhost
    port: 44444
    enable: true